name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++ meson make
      - uses: actions/checkout@v3

      - run: git clone https://github.com/hzeller/rpi-rgb-led-matrix/ rgbmatrix
      - run: make -C rgbmatrix

      - run: meson build/ -Dcpp_args=-I$PWD/rgbmatrix/include -Dcpp_link_args=-L$PWD/rgbmatrix/lib
      - run: ninja -C build
